/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScoringRouteImport } from './routes/scoring'
import { Route as RatingsRouteImport } from './routes/ratings'
import { Route as PdRouteImport } from './routes/pd'
import { Route as LgdRouteImport } from './routes/lgd'
import { Route as ExplainabilityRouteImport } from './routes/explainability'
import { Route as ExpectedLossRouteImport } from './routes/expected-loss'
import { Route as ConcentrationRouteImport } from './routes/concentration'
import { Route as BorrowersRouteImport } from './routes/borrowers'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BorrowersIdRouteImport } from './routes/borrowers.$id'
import { Route as AssessmentsNewRouteImport } from './routes/assessments.new'

const ScoringRoute = ScoringRouteImport.update({
  id: '/scoring',
  path: '/scoring',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingsRoute = RatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const PdRoute = PdRouteImport.update({
  id: '/pd',
  path: '/pd',
  getParentRoute: () => rootRouteImport,
} as any)
const LgdRoute = LgdRouteImport.update({
  id: '/lgd',
  path: '/lgd',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainabilityRoute = ExplainabilityRouteImport.update({
  id: '/explainability',
  path: '/explainability',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpectedLossRoute = ExpectedLossRouteImport.update({
  id: '/expected-loss',
  path: '/expected-loss',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcentrationRoute = ConcentrationRouteImport.update({
  id: '/concentration',
  path: '/concentration',
  getParentRoute: () => rootRouteImport,
} as any)
const BorrowersRoute = BorrowersRouteImport.update({
  id: '/borrowers',
  path: '/borrowers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BorrowersIdRoute = BorrowersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BorrowersRoute,
} as any)
const AssessmentsNewRoute = AssessmentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AssessmentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRouteWithChildren
  '/auth': typeof AuthRoute
  '/borrowers': typeof BorrowersRouteWithChildren
  '/concentration': typeof ConcentrationRoute
  '/expected-loss': typeof ExpectedLossRoute
  '/explainability': typeof ExplainabilityRoute
  '/lgd': typeof LgdRoute
  '/pd': typeof PdRoute
  '/ratings': typeof RatingsRoute
  '/scoring': typeof ScoringRoute
  '/assessments/new': typeof AssessmentsNewRoute
  '/borrowers/$id': typeof BorrowersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRouteWithChildren
  '/auth': typeof AuthRoute
  '/borrowers': typeof BorrowersRouteWithChildren
  '/concentration': typeof ConcentrationRoute
  '/expected-loss': typeof ExpectedLossRoute
  '/explainability': typeof ExplainabilityRoute
  '/lgd': typeof LgdRoute
  '/pd': typeof PdRoute
  '/ratings': typeof RatingsRoute
  '/scoring': typeof ScoringRoute
  '/assessments/new': typeof AssessmentsNewRoute
  '/borrowers/$id': typeof BorrowersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRouteWithChildren
  '/auth': typeof AuthRoute
  '/borrowers': typeof BorrowersRouteWithChildren
  '/concentration': typeof ConcentrationRoute
  '/expected-loss': typeof ExpectedLossRoute
  '/explainability': typeof ExplainabilityRoute
  '/lgd': typeof LgdRoute
  '/pd': typeof PdRoute
  '/ratings': typeof RatingsRoute
  '/scoring': typeof ScoringRoute
  '/assessments/new': typeof AssessmentsNewRoute
  '/borrowers/$id': typeof BorrowersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessments'
    | '/auth'
    | '/borrowers'
    | '/concentration'
    | '/expected-loss'
    | '/explainability'
    | '/lgd'
    | '/pd'
    | '/ratings'
    | '/scoring'
    | '/assessments/new'
    | '/borrowers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessments'
    | '/auth'
    | '/borrowers'
    | '/concentration'
    | '/expected-loss'
    | '/explainability'
    | '/lgd'
    | '/pd'
    | '/ratings'
    | '/scoring'
    | '/assessments/new'
    | '/borrowers/$id'
  id:
    | '__root__'
    | '/'
    | '/assessments'
    | '/auth'
    | '/borrowers'
    | '/concentration'
    | '/expected-loss'
    | '/explainability'
    | '/lgd'
    | '/pd'
    | '/ratings'
    | '/scoring'
    | '/assessments/new'
    | '/borrowers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentsRoute: typeof AssessmentsRouteWithChildren
  AuthRoute: typeof AuthRoute
  BorrowersRoute: typeof BorrowersRouteWithChildren
  ConcentrationRoute: typeof ConcentrationRoute
  ExpectedLossRoute: typeof ExpectedLossRoute
  ExplainabilityRoute: typeof ExplainabilityRoute
  LgdRoute: typeof LgdRoute
  PdRoute: typeof PdRoute
  RatingsRoute: typeof RatingsRoute
  ScoringRoute: typeof ScoringRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scoring': {
      id: '/scoring'
      path: '/scoring'
      fullPath: '/scoring'
      preLoaderRoute: typeof ScoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratings': {
      id: '/ratings'
      path: '/ratings'
      fullPath: '/ratings'
      preLoaderRoute: typeof RatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pd': {
      id: '/pd'
      path: '/pd'
      fullPath: '/pd'
      preLoaderRoute: typeof PdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lgd': {
      id: '/lgd'
      path: '/lgd'
      fullPath: '/lgd'
      preLoaderRoute: typeof LgdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explainability': {
      id: '/explainability'
      path: '/explainability'
      fullPath: '/explainability'
      preLoaderRoute: typeof ExplainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expected-loss': {
      id: '/expected-loss'
      path: '/expected-loss'
      fullPath: '/expected-loss'
      preLoaderRoute: typeof ExpectedLossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concentration': {
      id: '/concentration'
      path: '/concentration'
      fullPath: '/concentration'
      preLoaderRoute: typeof ConcentrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/borrowers': {
      id: '/borrowers'
      path: '/borrowers'
      fullPath: '/borrowers'
      preLoaderRoute: typeof BorrowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/borrowers/$id': {
      id: '/borrowers/$id'
      path: '/$id'
      fullPath: '/borrowers/$id'
      preLoaderRoute: typeof BorrowersIdRouteImport
      parentRoute: typeof BorrowersRoute
    }
    '/assessments/new': {
      id: '/assessments/new'
      path: '/new'
      fullPath: '/assessments/new'
      preLoaderRoute: typeof AssessmentsNewRouteImport
      parentRoute: typeof AssessmentsRoute
    }
  }
}

interface AssessmentsRouteChildren {
  AssessmentsNewRoute: typeof AssessmentsNewRoute
}

const AssessmentsRouteChildren: AssessmentsRouteChildren = {
  AssessmentsNewRoute: AssessmentsNewRoute,
}

const AssessmentsRouteWithChildren = AssessmentsRoute._addFileChildren(
  AssessmentsRouteChildren,
)

interface BorrowersRouteChildren {
  BorrowersIdRoute: typeof BorrowersIdRoute
}

const BorrowersRouteChildren: BorrowersRouteChildren = {
  BorrowersIdRoute: BorrowersIdRoute,
}

const BorrowersRouteWithChildren = BorrowersRoute._addFileChildren(
  BorrowersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentsRoute: AssessmentsRouteWithChildren,
  AuthRoute: AuthRoute,
  BorrowersRoute: BorrowersRouteWithChildren,
  ConcentrationRoute: ConcentrationRoute,
  ExpectedLossRoute: ExpectedLossRoute,
  ExplainabilityRoute: ExplainabilityRoute,
  LgdRoute: LgdRoute,
  PdRoute: PdRoute,
  RatingsRoute: RatingsRoute,
  ScoringRoute: ScoringRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
